[package]
name = "didcomm-protocols"
version = "0.1.0"
edition = "2021"

[dependencies]
didcomm-rs = { version = "0.7.2", git = "https://github.com/decentralized-identity/didcomm-rs" }
did-key = { version = "*" }
serde_json = { version = "1" }
